# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then call a random question with `pick()` an hint towards its solution with
`hint(n)` and the answer with `answer(n)`, where n is the number of the picked question.

In [5]:
%run initialise.py

In [11]:
import torch as torch
from einops import rearrange, repeat, reduce

In [6]:
pick()

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [9]:
torch.arange(9).reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [10]:
pick()

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [16]:
repeat(torch.arange(5), "x -> x c", c=5)

tensor([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]])

In [17]:
pick()

97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [29]:
A = torch.rand(4)
B = torch.rand(4)
A
B

#inner
torch.einsum("i,i->", A, B)
#outer
torch.einsum("i,j -> ij", A, B)
#mul
torch.einsum("i,i -> i", A, B)
#sum
torch.einsum("i->", A)

tensor(1.8091)

In [28]:
answer(97)

# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


In [31]:
pick()

14. Create a random vector of size 30 and find the mean value (★☆☆)


In [32]:
torch.rand(30).mean()

tensor(0.4622)

In [34]:
pick()

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


In [43]:
import numpy as np
X = torch.rand(4)
Y = torch.rand(6)
1.0/np.subtract.outer(X, Y)

array([[  2.6208339, -25.229996 ,  -2.2079577, -24.332685 ,   6.427515 ,
          4.552724 ],
       [  2.7794762, -16.283121 ,  -2.1066597, -15.904594 ,   7.4736633,
          5.053803 ],
       [  2.0826397,  16.95876  ,  -2.822425 ,  17.389807 ,   3.9341726,
          3.1421773],
       [-55.215454 ,  -2.2763271,  -1.1729159,  -2.2687786,  -4.096888 ,
         -5.5549355]], dtype=float32)

In [36]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


In [48]:
pick()

40. Create a random vector of size 10 and sort it (★★☆)


In [49]:
torch.rand(10).sort()

torch.return_types.sort(
values=tensor([0.0297, 0.0406, 0.0656, 0.0982, 0.1086, 0.2711, 0.4085, 0.4348, 0.7586,
        0.8887]),
indices=tensor([4, 3, 6, 1, 7, 5, 8, 2, 0, 9]))

In [50]:
pick()

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [57]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


In [59]:
torch.diag(torch.arange(1, 5), -1)

tensor([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]])

In [60]:
pick()

96. Given a two dimensional array, how to extract unique rows? (★★★)


In [61]:
answer(96)

# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)


In [66]:
Z = torch.randint(0, 2, (6,3))
torch.unique(Z, dim=0)

tensor([[0, 0, 0],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0]])